#!/bin/bash

# Script to update Supabase types locally
# Usage: ./scripts/update-types.sh

set -e

echo "🔄 Updating Supabase database types..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Check if SUPABASE_ACCESS_TOKEN is set
if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
    echo "⚠️  Warning: SUPABASE_ACCESS_TOKEN not set"
    echo "   You may need to login with: npx supabase login"
fi

# Project configuration
PROJECT_ID="lgveqfnpkxvzbnnwuled"
OUTPUT_FILE="database.types.ts"

# Generate types
echo "📡 Fetching schema from Supabase project: $PROJECT_ID"
npx supabase gen types typescript \
    --project-id $PROJECT_ID \
    --schema public \
    > $OUTPUT_FILE.tmp

# Check if generation was successful
if [ $? -eq 0 ]; then
    # Add header comment to the file
    cat > $OUTPUT_FILE << EOF
/**
 * Supabase Database Types
 * 
 * Auto-generated from Supabase project: $PROJECT_ID
 * Generated at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'npm run update-types' to regenerate
 */

EOF
    
    # Append the generated types
    cat $OUTPUT_FILE.tmp >> $OUTPUT_FILE
    rm $OUTPUT_FILE.tmp
    
    echo "✅ Types updated successfully!"
    echo ""
    echo "📄 Output file: $OUTPUT_FILE"
    
    # Check for changes
    if git diff --quiet $OUTPUT_FILE 2>/dev/null; then
        echo "ℹ️  No changes detected in database types"
    else
        echo "✨ Database types have been updated"
        echo ""
        echo "Changes:"
        git diff --stat $OUTPUT_FILE 2>/dev/null || true
    fi
else
    echo "❌ Failed to generate types"
    rm -f $OUTPUT_FILE.tmp
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Next steps:"
echo "  1. Review the changes in $OUTPUT_FILE"
echo "  2. Commit if everything looks correct"
echo "  3. Push to trigger CI/CD pipeline"