name = "project-insights-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://lgveqfnpkxvzbnnwuled.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxndmVxZm5wa3h2emJubnd1bGVkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTI1NDE2NiwiZXhwIjoyMDcwODMwMTY2fQ.kIFo_ZSwO1uwpttYXxjSnYbBpUhwZhkW-ZGaiQLhKmA"
OPENAI_API_KEY = "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"

# Schedule to run every hour (optional)
[triggers]
crons = ["0 * * * *"]